Repository DaviBahiense/linkr, pull requests merged in 2022-04, with the labels that each got.

#22 Feat/comment
  src/components/Comments/Comment/CommentWrite.js
  src/components/Comments/index.js
  src/pages/Home/Post.js
Labels: bug

#25 Feat/new posts counter
  package-lock.json
  package.json
  src/pages/Home/Post.js
  src/pages/Home/index.js
  src/pages/Home/style.js
  src/services/api.js
Labels: enhancement

#26 fix comment message following in message
  src/components/Comments/Comment/index.js
  src/components/HashtagBox/index.js
Labels: bug

#27 Feat/share
  src/components/HashtagBox/index.js
  src/components/Modal/Modal.js
  src/components/Repost/Repost.js
  src/components/Repost/styleRepost.js
  src/components/Share/Share.js
  src/components/like/Like.js
  src/components/posts/Timeline.js
  src/pages/Home/Post.js
  src/pages/Home/style.js
  src/pages/Signup/index.js
  src/pages/User/User.js
  src/pages/User/style.js
  src/services/api.js
Labels: enhancement

#28 fix: buttons like and repost
  package-lock.json
  package.json
  src/components/HashtagBox/index.js
  src/components/Modal/ConfirmModal.js
  src/components/Repost/Repost.js
  src/components/Share/Share.js
  src/components/like/Like.js
  src/components/like/styledLike.js
Labels: enhancement

#29 Feat/follow features
  src/components/HashtagBox/index.js
  src/components/SearchBox/SearchBox.js
  src/components/SearchItem/SearchItem.js
  src/components/posts/Timeline.js
  src/pages/Hashtag/index.js
  src/pages/Home/Post.js
  src/pages/Home/index.js
  src/pages/User/User.js
  src/services/api.js
Labels: bug, enhancement

#30 Feat/follow features
  src/components/SearchBox/SearchBox.js
  src/components/SearchItem/SearchItem.js
  src/components/Share/Share.js
  src/components/TopBar/TopBar.js
  src/components/posts/Timeline.js
  src/pages/Hashtag/index.js
  src/pages/Home/index.js
  src/pages/User/User.js
Labels: bug
